# 服务端口号，默认80
server:
  port: 8866
spring:
  # 服务名称
  application:
    name: home-center


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/home_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: home
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379

  thymeleaf:
    cache=false:

mybatis-plus:
  configuration:
    #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*Mapper.xml

weather:
  provider: 和风
  config:
    hefeng:
      now-url: https://devapi.qweather.com/v7/weather/now?location=101250111&key=change-me

camera-video:
  base-path: V:\监控\xiaomi_camera_videos

image:
  base-path: V:\www\images\HC

notes:
  base-path: D:\www\notes