# 服务端口号，默认80
server:
  port: 8866
spring:
  # 服务名称
  application:
    name: home-center


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/home_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: home
    password: 123456
    # 指定类型为我们自己的
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  level:
    root: info
    com.wwh: debug


